namespace Core.Domain.Enums;
public enum ErrorCodes
{
    CONTENT_REQUIRED,
    CONTENT_LENGTH,
    POST_LIMIT_EXCEEDED,
    AUTHOR_ID_REQUIRED,
    ORIGINAL_POST_ID_REQUIRED,
    REPOST_LIMIT_EXCEEDED
}