version: '3.7'
services:
  db-mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posterr
      MYSQL_USER: posterr_user
      MYSQL_PASSWORD: poster7898
    ports:
      - "3306:3306"
    expose:
      - "3306"