version: "3.8"
services:
  dbmysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=posterr
      - MYSQL_USER=user
      - MYSQL_PASSWORD=lima7898
      - MYSQL_ROOT_PASSWORD=lima7898
    ports:
      - "33070:33070"
    expose:
      - "33070"
    container_name: posterr_db
    # volumes:
    #   - mysql-data-posterr:/var/lib/mysql
    # networks:
    #   - posterr-network

  # webapi:
  #   build:
  #     context: ./Backend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5700:80"
  #   container_name: posterr_api
  #   networks:
  #     - posterr-network
  #   depends_on:
  #     - dbpostgres

  # frontend:
  #   build:
  #     context: ./Frontend/Posterr
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   container_name: posterr_frontend
  #   networks:
  #     - posterr-network
  #   depends_on:
  #     - dbpostgres
  #     - webapi
# volumes:
#   postgres-data-posterr:

# networks:
#   posterr-network:
#     driver: bridge

