version: '3.7'
services:
  db-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posterr
      MYSQL_USER: posterr_user
      MYSQL_PASSWORD: posterr7898
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: [ 
          "CMD", 
          "mysqladmin", 
          "ping", 
          "-h", 
          "localhost", 
          # "-u", 
          # "posterr_user", 
          # "-p", 
          # "root"
        ]
      interval: 5s
      timeout: 10s
      retries: 5
  webapi:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3300:80"
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      #- db-mysql
      db-mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - webapi