version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: posterr
    ports:
      - "5432:5432"
    container_name: posterr_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rfcode-network
  
  webapi:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5500:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #  - CONNECTION_STRING=${CONNECTION_STRING}
    # depends_on:
    #   - db
    # networks:
    #   - app-network
    container_name: posterr_api
    networks:
      - posterr-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: posterr_frontend
    networks:
      - posterr-network
    depends_on:
      - postgres
      - webapi


volumes:
  postgres-data:

networks:
  rfcode-network:
    driver: bridge
    


