version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: posterr
    ports:
      - "5433:5433"
    container_name: posterr_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - posterr-network
  
  webapi:
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "5700:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #  - CONNECTION_STRING=${CONNECTION_STRING}
    # depends_on:
    #   - db
    # networks:
    #   - app-network
    container_name: posterr_api
    networks:
      - posterr-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./Frontend/Posterr
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: posterr_frontend
    networks:
      - posterr-network
    depends_on:
      - postgres
      - webapi


volumes:
  postgres-data:

networks:
  posterr-network:
    driver: bridge
    


